language: python
python:
  - 3.7
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install -U pytest-cov
  - pip install -U codecov
install:
  - python setup.py develop
script:
  - pytest --cov=idapi --cov-report=term-missing -vv -s
after_success:
  - codecov